title: AntiPágina
description: Mis proyectos
theme: just-the-docs

url: https://antitunos.github.io

# logo: "/assets/images/just-the-docs.png"

# favicon_ico: "/assets/images/favicon/favicon.ico"

search_enabled: true

color_scheme: blue